//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.08 at 09:15:21 AM EET 
//


package eu.ubitech.cyberattackanalyzer.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IPDescriptor"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="IPAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LocationDescriptor" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="CountryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="RegionName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="RegionCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ZipCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="MetroCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="BlacklistingDescriptor" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="BlacklistingLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="AdversaryHostDescriptor" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="NetworkRange" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="NetworkSize" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="NetworkName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ProvName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="NetworkCategory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="AdversarySystemDescriptor" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="OSDescriptor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="PortsDescriptor" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="PortDescriptor" maxOccurs="unbounded"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="ProgramName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                     &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="ReverseIPDescriptor" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="VirtualHost" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="VirtualHostname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="AmountOfVirtualHosts" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DateDescriptor"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Fulldate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Day" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MaliciousActionDescriptor" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="AttackType"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="AuthenticationAbuse"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="AttackContext" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ipDescriptor",
    "dateDescriptor",
    "maliciousActionDescriptor"
})
@XmlRootElement(name = "Attack")
public class Attack {

    @XmlElement(name = "IPDescriptor", required = true)
    protected Attack.IPDescriptor ipDescriptor;
    @XmlElement(name = "DateDescriptor", required = true)
    protected Attack.DateDescriptor dateDescriptor;
    @XmlElement(name = "MaliciousActionDescriptor")
    protected Attack.MaliciousActionDescriptor maliciousActionDescriptor;

    /**
     * Gets the value of the ipDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link Attack.IPDescriptor }
     *     
     */
    public Attack.IPDescriptor getIPDescriptor() {
        return ipDescriptor;
    }

    /**
     * Sets the value of the ipDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attack.IPDescriptor }
     *     
     */
    public void setIPDescriptor(Attack.IPDescriptor value) {
        this.ipDescriptor = value;
    }

    /**
     * Gets the value of the dateDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link Attack.DateDescriptor }
     *     
     */
    public Attack.DateDescriptor getDateDescriptor() {
        return dateDescriptor;
    }

    /**
     * Sets the value of the dateDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attack.DateDescriptor }
     *     
     */
    public void setDateDescriptor(Attack.DateDescriptor value) {
        this.dateDescriptor = value;
    }

    /**
     * Gets the value of the maliciousActionDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link Attack.MaliciousActionDescriptor }
     *     
     */
    public Attack.MaliciousActionDescriptor getMaliciousActionDescriptor() {
        return maliciousActionDescriptor;
    }

    /**
     * Sets the value of the maliciousActionDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attack.MaliciousActionDescriptor }
     *     
     */
    public void setMaliciousActionDescriptor(Attack.MaliciousActionDescriptor value) {
        this.maliciousActionDescriptor = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Fulldate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Day" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fulldate",
        "year",
        "month",
        "day",
        "time"
    })
    public static class DateDescriptor {

        @XmlElement(name = "Fulldate", required = true)
        protected String fulldate;
        @XmlElement(name = "Year", required = true)
        protected String year;
        @XmlElement(name = "Month", required = true)
        protected String month;
        @XmlElement(name = "Day", required = true)
        protected String day;
        @XmlElement(name = "Time", required = true)
        protected String time;

        /**
         * Gets the value of the fulldate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFulldate() {
            return fulldate;
        }

        /**
         * Sets the value of the fulldate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFulldate(String value) {
            this.fulldate = value;
        }

        /**
         * Gets the value of the year property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getYear() {
            return year;
        }

        /**
         * Sets the value of the year property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setYear(String value) {
            this.year = value;
        }

        /**
         * Gets the value of the month property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMonth() {
            return month;
        }

        /**
         * Sets the value of the month property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMonth(String value) {
            this.month = value;
        }

        /**
         * Gets the value of the day property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDay() {
            return day;
        }

        /**
         * Sets the value of the day property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDay(String value) {
            this.day = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTime(String value) {
            this.time = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="IPAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LocationDescriptor" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="CountryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="RegionName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="RegionCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ZipCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="MetroCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="BlacklistingDescriptor" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="BlacklistingLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="AdversaryHostDescriptor" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="NetworkRange" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="NetworkSize" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="NetworkName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ProvName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="NetworkCategory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="AdversarySystemDescriptor" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="OSDescriptor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="PortsDescriptor" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="PortDescriptor" maxOccurs="unbounded"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="ProgramName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                           &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ReverseIPDescriptor" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="VirtualHost" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="VirtualHostname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="AmountOfVirtualHosts" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ipAddress",
        "locationDescriptor",
        "blacklistingDescriptor",
        "adversaryHostDescriptor",
        "adversarySystemDescriptor",
        "reverseIPDescriptor"
    })
    public static class IPDescriptor {

        @XmlElement(name = "IPAddress", required = true)
        protected String ipAddress;
        @XmlElement(name = "LocationDescriptor")
        protected Attack.IPDescriptor.LocationDescriptor locationDescriptor;
        @XmlElement(name = "BlacklistingDescriptor")
        protected Attack.IPDescriptor.BlacklistingDescriptor blacklistingDescriptor;
        @XmlElement(name = "AdversaryHostDescriptor")
        protected Attack.IPDescriptor.AdversaryHostDescriptor adversaryHostDescriptor;
        @XmlElement(name = "AdversarySystemDescriptor")
        protected Attack.IPDescriptor.AdversarySystemDescriptor adversarySystemDescriptor;
        @XmlElement(name = "ReverseIPDescriptor")
        protected Attack.IPDescriptor.ReverseIPDescriptor reverseIPDescriptor;

        /**
         * Gets the value of the ipAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIPAddress() {
            return ipAddress;
        }

        /**
         * Sets the value of the ipAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIPAddress(String value) {
            this.ipAddress = value;
        }

        /**
         * Gets the value of the locationDescriptor property.
         * 
         * @return
         *     possible object is
         *     {@link Attack.IPDescriptor.LocationDescriptor }
         *     
         */
        public Attack.IPDescriptor.LocationDescriptor getLocationDescriptor() {
            return locationDescriptor;
        }

        /**
         * Sets the value of the locationDescriptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link Attack.IPDescriptor.LocationDescriptor }
         *     
         */
        public void setLocationDescriptor(Attack.IPDescriptor.LocationDescriptor value) {
            this.locationDescriptor = value;
        }

        /**
         * Gets the value of the blacklistingDescriptor property.
         * 
         * @return
         *     possible object is
         *     {@link Attack.IPDescriptor.BlacklistingDescriptor }
         *     
         */
        public Attack.IPDescriptor.BlacklistingDescriptor getBlacklistingDescriptor() {
            return blacklistingDescriptor;
        }

        /**
         * Sets the value of the blacklistingDescriptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link Attack.IPDescriptor.BlacklistingDescriptor }
         *     
         */
        public void setBlacklistingDescriptor(Attack.IPDescriptor.BlacklistingDescriptor value) {
            this.blacklistingDescriptor = value;
        }

        /**
         * Gets the value of the adversaryHostDescriptor property.
         * 
         * @return
         *     possible object is
         *     {@link Attack.IPDescriptor.AdversaryHostDescriptor }
         *     
         */
        public Attack.IPDescriptor.AdversaryHostDescriptor getAdversaryHostDescriptor() {
            return adversaryHostDescriptor;
        }

        /**
         * Sets the value of the adversaryHostDescriptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link Attack.IPDescriptor.AdversaryHostDescriptor }
         *     
         */
        public void setAdversaryHostDescriptor(Attack.IPDescriptor.AdversaryHostDescriptor value) {
            this.adversaryHostDescriptor = value;
        }

        /**
         * Gets the value of the adversarySystemDescriptor property.
         * 
         * @return
         *     possible object is
         *     {@link Attack.IPDescriptor.AdversarySystemDescriptor }
         *     
         */
        public Attack.IPDescriptor.AdversarySystemDescriptor getAdversarySystemDescriptor() {
            return adversarySystemDescriptor;
        }

        /**
         * Sets the value of the adversarySystemDescriptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link Attack.IPDescriptor.AdversarySystemDescriptor }
         *     
         */
        public void setAdversarySystemDescriptor(Attack.IPDescriptor.AdversarySystemDescriptor value) {
            this.adversarySystemDescriptor = value;
        }

        /**
         * Gets the value of the reverseIPDescriptor property.
         * 
         * @return
         *     possible object is
         *     {@link Attack.IPDescriptor.ReverseIPDescriptor }
         *     
         */
        public Attack.IPDescriptor.ReverseIPDescriptor getReverseIPDescriptor() {
            return reverseIPDescriptor;
        }

        /**
         * Sets the value of the reverseIPDescriptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link Attack.IPDescriptor.ReverseIPDescriptor }
         *     
         */
        public void setReverseIPDescriptor(Attack.IPDescriptor.ReverseIPDescriptor value) {
            this.reverseIPDescriptor = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="NetworkRange" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="NetworkSize" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="NetworkName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ProvName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="NetworkCategory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "networkRange",
            "networkSize",
            "networkName",
            "provName",
            "networkCategory"
        })
        public static class AdversaryHostDescriptor {

            @XmlElement(name = "NetworkRange", required = true)
            protected String networkRange;
            @XmlElement(name = "NetworkSize")
            protected int networkSize;
            @XmlElement(name = "NetworkName", required = true)
            protected String networkName;
            @XmlElement(name = "ProvName", required = true)
            protected String provName;
            @XmlElement(name = "NetworkCategory", required = true)
            protected String networkCategory;

            /**
             * Gets the value of the networkRange property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNetworkRange() {
                return networkRange;
            }

            /**
             * Sets the value of the networkRange property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNetworkRange(String value) {
                this.networkRange = value;
            }

            /**
             * Gets the value of the networkSize property.
             * 
             */
            public int getNetworkSize() {
                return networkSize;
            }

            /**
             * Sets the value of the networkSize property.
             * 
             */
            public void setNetworkSize(int value) {
                this.networkSize = value;
            }

            /**
             * Gets the value of the networkName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNetworkName() {
                return networkName;
            }

            /**
             * Sets the value of the networkName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNetworkName(String value) {
                this.networkName = value;
            }

            /**
             * Gets the value of the provName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProvName() {
                return provName;
            }

            /**
             * Sets the value of the provName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProvName(String value) {
                this.provName = value;
            }

            /**
             * Gets the value of the networkCategory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNetworkCategory() {
                return networkCategory;
            }

            /**
             * Sets the value of the networkCategory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNetworkCategory(String value) {
                this.networkCategory = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="OSDescriptor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="PortsDescriptor" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="PortDescriptor" maxOccurs="unbounded"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="ProgramName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *                 &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "osDescriptor",
            "portsDescriptor"
        })
        public static class AdversarySystemDescriptor {

            @XmlElement(name = "OSDescriptor")
            protected String osDescriptor;
            @XmlElement(name = "PortsDescriptor")
            protected Attack.IPDescriptor.AdversarySystemDescriptor.PortsDescriptor portsDescriptor;

            /**
             * Gets the value of the osDescriptor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOSDescriptor() {
                return osDescriptor;
            }

            /**
             * Sets the value of the osDescriptor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOSDescriptor(String value) {
                this.osDescriptor = value;
            }

            /**
             * Gets the value of the portsDescriptor property.
             * 
             * @return
             *     possible object is
             *     {@link Attack.IPDescriptor.AdversarySystemDescriptor.PortsDescriptor }
             *     
             */
            public Attack.IPDescriptor.AdversarySystemDescriptor.PortsDescriptor getPortsDescriptor() {
                return portsDescriptor;
            }

            /**
             * Sets the value of the portsDescriptor property.
             * 
             * @param value
             *     allowed object is
             *     {@link Attack.IPDescriptor.AdversarySystemDescriptor.PortsDescriptor }
             *     
             */
            public void setPortsDescriptor(Attack.IPDescriptor.AdversarySystemDescriptor.PortsDescriptor value) {
                this.portsDescriptor = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="PortDescriptor" maxOccurs="unbounded"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="ProgramName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *       &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "portDescriptor"
            })
            public static class PortsDescriptor {

                @XmlElement(name = "PortDescriptor", required = true)
                protected List<Attack.IPDescriptor.AdversarySystemDescriptor.PortsDescriptor.PortDescriptor> portDescriptor;
                @XmlAttribute(name = "amount")
                @XmlSchemaType(name = "anySimpleType")
                protected String amount;

                /**
                 * Gets the value of the portDescriptor property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the portDescriptor property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPortDescriptor().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Attack.IPDescriptor.AdversarySystemDescriptor.PortsDescriptor.PortDescriptor }
                 * 
                 * 
                 */
                public List<Attack.IPDescriptor.AdversarySystemDescriptor.PortsDescriptor.PortDescriptor> getPortDescriptor() {
                    if (portDescriptor == null) {
                        portDescriptor = new ArrayList<Attack.IPDescriptor.AdversarySystemDescriptor.PortsDescriptor.PortDescriptor>();
                    }
                    return this.portDescriptor;
                }

                /**
                 * Gets the value of the amount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAmount() {
                    return amount;
                }

                /**
                 * Sets the value of the amount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAmount(String value) {
                    this.amount = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="ProgramName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "programName",
                    "port"
                })
                public static class PortDescriptor {

                    @XmlElement(name = "ProgramName", required = true)
                    protected String programName;
                    @XmlElement(name = "Port", required = true)
                    protected String port;

                    /**
                     * Gets the value of the programName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getProgramName() {
                        return programName;
                    }

                    /**
                     * Sets the value of the programName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setProgramName(String value) {
                        this.programName = value;
                    }

                    /**
                     * Gets the value of the port property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPort() {
                        return port;
                    }

                    /**
                     * Sets the value of the port property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPort(String value) {
                        this.port = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="BlacklistingLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "blacklistingLevel"
        })
        public static class BlacklistingDescriptor {

            @XmlElement(name = "BlacklistingLevel")
            protected String blacklistingLevel;

            /**
             * Gets the value of the blacklistingLevel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBlacklistingLevel() {
                return blacklistingLevel;
            }

            /**
             * Sets the value of the blacklistingLevel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBlacklistingLevel(String value) {
                this.blacklistingLevel = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="CountryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="RegionName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="RegionCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ZipCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="MetroCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "countryName",
            "countryCode",
            "regionName",
            "regionCode",
            "city",
            "zipCode",
            "timeZone",
            "latitude",
            "longitude",
            "metroCode"
        })
        public static class LocationDescriptor {

            @XmlElement(name = "CountryName", required = true)
            protected String countryName;
            @XmlElement(name = "CountryCode", required = true)
            protected String countryCode;
            @XmlElement(name = "RegionName", required = true)
            protected String regionName;
            @XmlElement(name = "RegionCode", required = true)
            protected String regionCode;
            @XmlElement(name = "City", required = true)
            protected String city;
            @XmlElement(name = "ZipCode", required = true)
            protected String zipCode;
            @XmlElement(name = "TimeZone", required = true)
            protected String timeZone;
            @XmlElement(name = "Latitude", required = true)
            protected String latitude;
            @XmlElement(name = "Longitude", required = true)
            protected String longitude;
            @XmlElement(name = "MetroCode", required = true)
            protected String metroCode;

            /**
             * Gets the value of the countryName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountryName() {
                return countryName;
            }

            /**
             * Sets the value of the countryName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountryName(String value) {
                this.countryName = value;
            }

            /**
             * Gets the value of the countryCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountryCode() {
                return countryCode;
            }

            /**
             * Sets the value of the countryCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountryCode(String value) {
                this.countryCode = value;
            }

            /**
             * Gets the value of the regionName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegionName() {
                return regionName;
            }

            /**
             * Sets the value of the regionName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegionName(String value) {
                this.regionName = value;
            }

            /**
             * Gets the value of the regionCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegionCode() {
                return regionCode;
            }

            /**
             * Sets the value of the regionCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegionCode(String value) {
                this.regionCode = value;
            }

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCity() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCity(String value) {
                this.city = value;
            }

            /**
             * Gets the value of the zipCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZipCode() {
                return zipCode;
            }

            /**
             * Sets the value of the zipCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZipCode(String value) {
                this.zipCode = value;
            }

            /**
             * Gets the value of the timeZone property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimeZone() {
                return timeZone;
            }

            /**
             * Sets the value of the timeZone property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimeZone(String value) {
                this.timeZone = value;
            }

            /**
             * Gets the value of the latitude property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLatitude() {
                return latitude;
            }

            /**
             * Sets the value of the latitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLatitude(String value) {
                this.latitude = value;
            }

            /**
             * Gets the value of the longitude property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLongitude() {
                return longitude;
            }

            /**
             * Sets the value of the longitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLongitude(String value) {
                this.longitude = value;
            }

            /**
             * Gets the value of the metroCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMetroCode() {
                return metroCode;
            }

            /**
             * Sets the value of the metroCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMetroCode(String value) {
                this.metroCode = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="VirtualHost" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="VirtualHostname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="AmountOfVirtualHosts" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "virtualHost"
        })
        public static class ReverseIPDescriptor {

            @XmlElement(name = "VirtualHost", required = true)
            protected List<Attack.IPDescriptor.ReverseIPDescriptor.VirtualHost> virtualHost;
            @XmlAttribute(name = "AmountOfVirtualHosts")
            protected Integer amountOfVirtualHosts;

            /**
             * Gets the value of the virtualHost property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the virtualHost property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getVirtualHost().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Attack.IPDescriptor.ReverseIPDescriptor.VirtualHost }
             * 
             * 
             */
            public List<Attack.IPDescriptor.ReverseIPDescriptor.VirtualHost> getVirtualHost() {
                if (virtualHost == null) {
                    virtualHost = new ArrayList<Attack.IPDescriptor.ReverseIPDescriptor.VirtualHost>();
                }
                return this.virtualHost;
            }

            /**
             * Gets the value of the amountOfVirtualHosts property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getAmountOfVirtualHosts() {
                return amountOfVirtualHosts;
            }

            /**
             * Sets the value of the amountOfVirtualHosts property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setAmountOfVirtualHosts(Integer value) {
                this.amountOfVirtualHosts = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="VirtualHostname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "virtualHostname"
            })
            public static class VirtualHost {

                @XmlElement(name = "VirtualHostname", required = true)
                protected String virtualHostname;

                /**
                 * Gets the value of the virtualHostname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVirtualHostname() {
                    return virtualHostname;
                }

                /**
                 * Sets the value of the virtualHostname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVirtualHostname(String value) {
                    this.virtualHostname = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="AttackType"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="AuthenticationAbuse"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="AttackContext" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attackType",
        "attackContext"
    })
    public static class MaliciousActionDescriptor {

        @XmlElement(name = "AttackType", required = true)
        protected String attackType;
        @XmlElement(name = "AttackContext")
        protected List<String> attackContext;

        /**
         * Gets the value of the attackType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttackType() {
            return attackType;
        }

        /**
         * Sets the value of the attackType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttackType(String value) {
            this.attackType = value;
        }

        /**
         * Gets the value of the attackContext property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attackContext property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttackContext().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttackContext() {
            if (attackContext == null) {
                attackContext = new ArrayList<String>();
            }
            return this.attackContext;
        }

    }

}
